// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  artist_slice: dynamic(() => import("./ArtistSlice")),
  blog_list: dynamic(() => import("./BlogList")),
  call_to_action: dynamic(() => import("./CallToAction")),
  contact: dynamic(() => import("./Contact")),
  eventos: dynamic(() => import("./EventList")),
  hero: dynamic(() => import("./Hero")),
  hero_2: dynamic(() => import("./Hero2")),
  post: dynamic(() => import("./Post")),
  rich_text: dynamic(() => import("./RichText")),
  single_event: dynamic(() => import("./SingleEvent")),
};
